FROM debian:bullseye-slim AS compiler-setup
RUN apt update
RUN apt install -y wget xz-utils make gcc libtinfo5 llvm-9-dev
RUN wget https://downloads.haskell.org/ghc/8.10.1-rc1/ghc-8.10.0.20200123-armv7-deb9-linux.tar.xz
RUN tar xaf ghc-8.10.0.20200123-armv7-deb9-linux.tar.xz
WORKDIR /ghc-8.10.0.20200123
RUN ./configure --prefix=/opt/ghc
RUN make install

FROM debian:bullseye-slim
RUN apt update
RUN apt -y upgrade
RUN apt install -y make gcc libtinfo5 wget llvm-9
RUN wget -qO- https://get.haskellstack.org/ | sh
COPY --from=compiler-setup /opt /opt
ENV PATH="/opt/ghc/bin:${PATH}"
#ENTRYPOINT /bin/bash
ENTRYPOINT stack build --allow-different-user

# docker build -t haskell-build-4 .
# pwd=$(pwd)
#
# docker run -it --rm -v $pwd:/src -v /home/fuszenecker/.stack:/root/.stack -w /src haskell-build-4
