# Dockerfile
# ----------

FROM debian:bullseye-slim
RUN apt update
RUN apt -y upgrade
RUN apt install -y curl make llvm-9-dev libtinfo5
RUN curl -sSL https://get.haskellstack.org/ | sh
CMD ["stack", "install", "--allow-different-user"]


# Build the image:
# ----------------

docker build -t haskell-build .


# Run the image:
# --------------

#!/usr/bin/env sh
docker run -it --rm -v $(pwd):/src -v /home/$(whoami)/.stack:/root/.stack -v /home/$(whoami)/.local:/root/.local -w /src haskell-build $*

sudo chown $(whoami) -R ~/.stack/*
sudo chown $(whoami) -R .stack-work
sudo chown $(whoami) -R ~/.local
sudo chown $(whoami) stack.yaml.lock *.cabal


# Dockerfile - old
# ----------------

FROM debian:bullseye-slim AS compiler-setup
RUN apt update
RUN apt install -y wget lzip make gcc libtinfo5 llvm-9-dev
RUN wget https://downloads.haskell.org/ghc/8.10.1/ghc-8.10.1-armv7-deb9-linux.tar.lz
RUN tar xaf ghc-8.10.1-armv7-deb9-linux.tar.lz
WORKDIR /ghc-8.10.1
RUN ./configure --prefix=/opt/ghc
RUN make install
RUN rm -rf /opt/ghc/share

FROM debian:bullseye-slim
RUN apt update
RUN apt -y upgrade
RUN apt install -y make gcc libtinfo5 wget llvm-9
RUN wget -qO- https://get.haskellstack.org/ | sh
COPY --from=compiler-setup /opt /opt
ENV PATH="/opt/ghc/bin:${PATH}"
CMD ["stack", "install", "--allow-different-user"]
