system-ghc: true
skip-ghc-check: true
allow-newer: true
colour: always
recommend-stack-upgrade: true

# ghc-options:
#    # All packages
#    "$locals": -Wall
#    "$targets": -Werror
#    "$everything": -O2
#    some-package: -DSOME_CPP_FLAG

templates:
    params:
        author-name: Róbert Fuszenecker
        author-email: robert.fuszenecker@outlook.com
        category: demo
        copyright: 'Copyright © Róbert Fuszenecker, 2020'
        github-username: fuszenecker
