system-ghc: true
skip-ghc-check: true
allow-newer: true
colour: always
recommend-stack-upgrade: true

templates:
    params:
        author-name: Róbert Fuszenecker
        author-email: robert.fuszenecker@outlook.com
        category: demo
        copyright: 'Copyright © Róbert Fuszenecker, 2020'
        github-username: fuszenecker
